language: shell
before_install:
- sudo apt-get install texlive-latex-extra
script:
- tests/run.sh
- shellcheck --exclude=SC1004 bin/pdfjam
- "./travis-build.sh"
env:
  global:
  - GH_USER: DavidFirth
  - GH_REPO: pdfjam
  - secure:
    - GH_TOKEN: xU6FJtmLokxEfMQMppuNyzrqA9u6ieQPhqHVtBxZeblTqHpU/v6HzxRpDkcYHE530F8FmUgvw6k0oC2kKyOcHZkQI0Bt/LsHkj1rEgnKKobsRH3nlZxSJsKTP+D4WemecimJVg+QXkRkudIj2Q1RMvSqnwi4fSPQxc/85lEORxZakrBVU5liG4RSeOtWjfxgj7XwOyCXlP8WYJnDnxUN3XZDRnU2/r9yR4R1vFif7T9GKt2LI8Nyq7R5r50mQADQN3oQaIsgjW1CE94NmGiygsNY1qikg6q9cvk5cS0jEYo2fn1Mpu0SoT/xrZXOyEUegmVMHAX7NQNGQzrOu2APMZe7wU9Bs72sG0r6N7AYHYTsMyvTmfsCXtz1F4/vSYSxVnlhp9njMsVV2tYeDjH8tboaBP/KRR0hMVafWcMx+BpZ5RCckqHHF5iCnI+iyb+akLGiI/g8NenoxDrVTq06VR+dQrDo8F018GPUFgiiTeQ751kvOwK7FQq5JzC0k3/RGUwuwShkQb1NU5AwhhI3Ayab2TLhXFWMm+Ye9XHO7jS95QmUa0VWuEcV2kv0R7GV3KJcfXWTO4TWRAk5NnBLBPUj1kIbV5PQmfEerS5px7tj5gVXXxETgO2JzGXRqNINJlLUbq2EZERu5xIfElUjHZ+Io38X2YbvceOVekIzvNQ=