language: shell
before_install:
- sudo apt-get install texlive-latex-extra
script:
- tests/run.sh
- shellcheck --exclude=SC1004 bin/pdfjam
- ./travis-build.sh
env:
  global:
  - GH_USER: DavidFirth
  - GH_REPO: pdfjam
  